// Dicionário de aeroportos (expandido com 200+ aeroportos)
export const aeroDB = {
  // BRASIL
  FOR: 'Fortaleza',
  GRU: 'São Paulo (Guarulhos)',
  GIG: 'Rio de Janeiro (Galeão)',
  BSB: 'Brasília',
  CNF: 'Belo Horizonte (Confins)',
  SSA: 'Salvador',
  REC: 'Recife',
  POA: 'Porto Alegre',
  CWB: 'Curitiba',
  FLN: 'Florianópolis',
  MAO: 'Manaus',
  BEL: 'Belém',
  NAT: 'Natal',
  CGH: 'São Paulo (Congonhas)',
  VCP: 'Campinas (Viracopos)',
  SDU: 'Rio de Janeiro (Santos Dumont)',
  CGB: 'Cuiabá',
  VIX: 'Vitória',
  MCZ: 'Maceió',
  AJU: 'Aracaju',
  THE: 'Teresina',
  SLZ: 'São Luís',
  JPA: 'João Pessoa',
  PVH: 'Porto Velho',
  RBR: 'Rio Branco',
  BVB: 'Boa Vista',
  MCP: 'Macapá',
  PPB: 'Presidente Prudente',
  IGU: 'Foz do Iguaçu',
  UDI: 'Uberlândia',
  IOS: 'Ilhéus',
  JOI: 'Joinville',
  NVT: 'Navegantes',
  IMP: 'Imperatriz',
  UBA: 'Uberaba',
  CAC: 'Cascavel',
  PMW: 'Palmas',
  
  // AMÉRICA DO SUL
  EZE: 'Buenos Aires (Ezeiza)',
  AEP: 'Buenos Aires (Aeroparque)',
  COR: 'Córdoba',
  MDZ: 'Mendoza',
  SCL: 'Santiago',
  LIM: 'Lima',
  BOG: 'Bogotá',
  MDE: 'Medellín',
  CTG: 'Cartagena',
  CCS: 'Caracas',
  UIO: 'Quito',
  GYE: 'Guayaquil',
  ASU: 'Assunção',
  MVD: 'Montevidéu',
  LPB: 'La Paz',
  
  // AMÉRICA DO NORTE
  MIA: 'Miami',
  MCO: 'Orlando',
  JFK: 'Nova York (JFK)',
  LGA: 'Nova York (LaGuardia)',
  EWR: 'Newark',
  BOS: 'Boston',
  LAX: 'Los Angeles',
  SFO: 'São Francisco',
  LAS: 'Las Vegas',
  DFW: 'Dallas',
  IAH: 'Houston',
  ORD: 'Chicago (O\'Hare)',
  PHX: 'Phoenix',
  DEN: 'Denver',
  SEA: 'Seattle',
  ATL: 'Atlanta',
  MSP: 'Minneapolis',
  DTW: 'Detroit',
  PHL: 'Filadélfia',
  CLT: 'Charlotte',
  BNA: 'Nashville',
  AUS: 'Austin',
  SAN: 'San Diego',
  PDX: 'Portland',
  YYZ: 'Toronto',
  YUL: 'Montreal',
  YVR: 'Vancouver',
  YYC: 'Calgary',
  MEX: 'Cidade do México',
  CUN: 'Cancún',
  GDL: 'Guadalajara',
  MTY: 'Monterrey',
  PVR: 'Puerto Vallarta',
  SJD: 'Los Cabos',
  
  // EUROPA
  LIS: 'Lisboa',
  OPO: 'Porto',
  FAO: 'Faro',
  FNC: 'Funchal (Madeira)',
  MAD: 'Madrid',
  BCN: 'Barcelona',
  SVQ: 'Sevilha',
  VLC: 'Valência',
  AGP: 'Málaga',
  PMI: 'Palma de Maiorca',
  LHR: 'Londres (Heathrow)',
  LGW: 'Londres (Gatwick)',
  STN: 'Londres (Stansted)',
  LTN: 'Londres (Luton)',
  MAN: 'Manchester',
  EDI: 'Edimburgo',
  CDG: 'Paris (Charles de Gaulle)',
  ORY: 'Paris (Orly)',
  NCE: 'Nice',
  LYS: 'Lyon',
  MRS: 'Marselha',
  AMS: 'Amsterdã',
  FCO: 'Roma (Fiumicino)',
  CIA: 'Roma (Ciampino)',
  MXP: 'Milão (Malpensa)',
  LIN: 'Milão (Linate)',
  VCE: 'Veneza',
  NAP: 'Nápoles',
  FRA: 'Frankfurt',
  MUC: 'Munique',
  BER: 'Berlim',
  HAM: 'Hamburgo',
  DUS: 'Düsseldorf',
  CGN: 'Colônia',
  STR: 'Stuttgart',
  ZRH: 'Zurique',
  GVA: 'Genebra',
  VIE: 'Viena',
  PRG: 'Praga',
  BUD: 'Budapeste',
  WAW: 'Varsóvia',
  ATH: 'Atenas',
  DUB: 'Dublin',
  CPH: 'Copenhague',
  OSL: 'Oslo',
  STO: 'Estocolmo',
  HEL: 'Helsinque',
  BRU: 'Bruxelas',
  VIE: 'Viena',
  LIS: 'Lisboa',
  
  // ÁSIA
  DXB: 'Dubai',
  AUH: 'Abu Dhabi',
  DOH: 'Doha',
  IST: 'Istambul',
  SAW: 'Istambul (Sabiha)',
  JED: 'Jeddah',
  RUH: 'Riad',
  BKK: 'Bangkok',
  SIN: 'Singapura',
  KUL: 'Kuala Lumpur',
  HKG: 'Hong Kong',
  PVG: 'Xangai (Pudong)',
  SHA: 'Xangai (Hongqiao)',
  PEK: 'Pequim',
  CAN: 'Guangzhou',
  NRT: 'Tóquio (Narita)',
  HND: 'Tóquio (Haneda)',
  KIX: 'Osaka',
  ICN: 'Seul',
  MNL: 'Manila',
  DEL: 'Nova Délhi',
  BOM: 'Mumbai',
  BLR: 'Bangalore',
  HYD: 'Hyderabad',
  CGK: 'Jacarta',
  TPE: 'Taipei',
  
  // OCEANIA
  SYD: 'Sydney',
  MEL: 'Melbourne',
  BNE: 'Brisbane',
  PER: 'Perth',
  AKL: 'Auckland',
  CHC: 'Christchurch',
  WLG: 'Wellington',
  
  // ÁFRICA
  CPT: 'Cidade do Cabo',
  JNB: 'Joanesburgo',
  CAI: 'Cairo',
  NBO: 'Nairóbi',
  ADD: 'Adis Abeba',
  LOS: 'Lagos',
  ACC: 'Acra',
  CAS: 'Casablanca',
  ALG: 'Argel',
  TUN: 'Túnis',
  
  // CARIBE
  PUJ: 'Punta Cana',
  SDQ: 'Santo Domingo',
  SJU: 'San Juan',
  MBJ: 'Montego Bay',
  KIN: 'Kingston',
  NAS: 'Nassau',
  POS: 'Port of Spain',
  BGI: 'Bridgetown',
  CUR: 'Curaçao',
  AUA: 'Aruba',
};

// Dicionário de companhias aéreas
export const ciasDB = {
  TP: 'TAP',
  AD: 'Azul',
  G3: 'GOL',
  LA: 'LATAM',
  JJ: 'LATAM',
  AF: 'Air France',
  KL: 'KLM',
  LH: 'Lufthansa',
  IB: 'Iberia',
  BA: 'British Airways',
  AZ: 'ITA Airways',
  LX: 'Swiss',
  OS: 'Austrian',
  SN: 'Brussels Airlines',
  EK: 'Emirates',
  QR: 'Qatar Airways',
  EY: 'Etihad',
  TK: 'Turkish Airlines',
  AA: 'American Airlines',
  DL: 'Delta',
  UA: 'United',
  UX: 'Air Europa',
  AR: 'Aerolíneas Argentinas',
  CM: 'Copa Airlines',
  AM: 'Aeroméxico',
  AV: 'Avianca',
};
