// Dicionário de aeroportos
export const aeroDB = {
  FOR: 'Fortaleza',
  GRU: 'São Paulo (Guarulhos)',
  GIG: 'Rio de Janeiro (Galeão)',
  BSB: 'Brasília',
  CNF: 'Belo Horizonte',
  SSA: 'Salvador',
  REC: 'Recife',
  POA: 'Porto Alegre',
  CWB: 'Curitiba',
  FLN: 'Florianópolis',
  MAO: 'Manaus',
  BEL: 'Belém',
  NAT: 'Natal',
  CGH: 'São Paulo (Congonhas)',
  VCP: 'Campinas (Viracopos)',
  SDU: 'Rio de Janeiro (Santos Dumont)',
  EZE: 'Buenos Aires',
  SCL: 'Santiago',
  BOG: 'Bogotá',
  LIM: 'Lima',
  LIS: 'Lisboa',
  OPO: 'Porto',
  MAD: 'Madrid',
  BCN: 'Barcelona',
  LHR: 'Londres (Heathrow)',
  LGW: 'Londres (Gatwick)',
  CDG: 'Paris (Charles de Gaulle)',
  ORY: 'Paris (Orly)',
  AMS: 'Amsterdã',
  FCO: 'Roma (Fiumicino)',
  FRA: 'Frankfurt',
  MUC: 'Munique',
  ZRH: 'Zurique',
  MIA: 'Miami',
  MCO: 'Orlando',
  JFK: 'Nova York (JFK)',
  EWR: 'Newark',
  LAX: 'Los Angeles',
  DFW: 'Dallas',
  ORD: 'Chicago',
  YYZ: 'Toronto',
  MEX: 'Cidade do México',
  CUN: 'Cancún',
  DXB: 'Dubai',
  DOH: 'Doha',
  AUH: 'Abu Dhabi',
  IST: 'Istambul',
  NRT: 'Tóquio (Narita)',
  HND: 'Tóquio (Haneda)',
  SIN: 'Singapura',
  PVG: 'Xangai',
  PEK: 'Pequim',
  HKG: 'Hong Kong',
  SYD: 'Sydney',
  MEL: 'Melbourne',
};

// Dicionário de companhias aéreas
export const ciasDB = {
  TP: 'TAP',
  AD: 'Azul',
  G3: 'GOL',
  LA: 'LATAM',
  JJ: 'LATAM',
  AF: 'Air France',
  KL: 'KLM',
  LH: 'Lufthansa',
  IB: 'Iberia',
  BA: 'British Airways',
  AZ: 'ITA Airways',
  LX: 'Swiss',
  OS: 'Austrian',
  SN: 'Brussels Airlines',
  EK: 'Emirates',
  QR: 'Qatar Airways',
  EY: 'Etihad',
  TK: 'Turkish Airlines',
  AA: 'American Airlines',
  DL: 'Delta',
  UA: 'United',
  UX: 'Air Europa',
  AR: 'Aerolíneas Argentinas',
  CM: 'Copa Airlines',
  AM: 'Aeroméxico',
  AV: 'Avianca',
};
